### ISSUE TITLE
前端问题记录册

### ISSUE THREAD

**Issue by xwchris** [xwchris/blog#12]
### IOS Safari上给div绑定click事件没有反应
解决办法：
- 给CSS加上cursor：pointer
- 给div元素加上onclick='void(0)'
- 将div换成其他不受该特性影响的元素，比如a、button等

### 使用document.body.ScollTop获取的滚动值不正确
大部分浏览器可以使用`document.documentElement.scrollTop`来获取滚动条距离上面的高度，但是在Safari和edge中需要使用`document.body.scrollTop`来获取

### IE中引入使用外部svg文件的symbol不生效
Ie无法识别外部的svg文件中的symbol，svg元素必须要在必要在当前html中才可以识别，故可以通过可以请求svg文件后通过创建元素插入到当前页面中去，解决ie中的外部svg显示问题。

### -webkit-box-orient属性被autoprefixed移除
要保留该属性可以使用下面的写法，具体原因参考[此链接](https://github.com/postcss/autoprefixer/issues/776)
```
/* autoprefixer: ignore next */
-webkit-box-orient: vertical;
```

### 部分手机浏览器唤出软键盘后遮挡输入框
可以使用`Element.scrollToView()`来解决该问题，当元素被`focus`的时候，调用该方法滚动键盘到可视位置。

### IOS中使用input的focus方法无效[详细说明](https://stackoverflow.com/questions/12204571/mobile-safari-javascript-focus-method-on-inputfield-only-works-with-click)
IOS中为了不打扰用户，对弹出键盘的操作进行了限制。focus方法需要再用户操作后同步执行，无法异步执行。

### IOS中将软键盘的enter换成搜索[详细说明](https://stackoverflow.com/questions/4864167/show-search-button-in-iphone-ipad-safari-keyboard)
在IOS9以上要达到该目的需要以下代码
```html
<form action='.'>
    <input type='search' />
</form>
```
`input`需要被`form`包裹，同时`form`需要有`action`属性。

**Comment by ai** [comment]
This code is wrong (`autoprefixer: off/on` applies to the whole block, **not** to next lines):

```css
/* autoprefixer: off */
-webkit-box-orient: vertical;
/* autoprefixer: on */
```

Use:

```css
/* autoprefixer: ignore next */
-webkit-box-orient: vertical;
```

**Comment by xwchris** [comment]
@ai thanks a lot for your correction
